# Generated by Django 5.2.5 on 2025-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('excel', 'Excel'), ('powerbi', 'Power BI'), ('salesforce', 'Salesforce'), ('django', 'Django')], default='excel', max_length=20)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('github_link', models.URLField()),
                ('overview_pdf', models.FileField(upload_to='project_pdfs/')),
            ],
        ),
    ]
